<a href="https://colab.research.google.com/github/disha-g05/231A018_NLP-Experiments/blob/main/AIDS_Sem7_NLP_Experiment08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
print("Disha Gawade 231A018")
documents =[
"Solar panels convert sunlight into clean electricity.",
"Renewable energy can be generated from the sun using solar cells.",
"Electric vehicles help reduce greenhouse gas emissions in cities.",
"Photovoltaic systems capture solar energy to power homes.",
"Baking a cake requires precise measurements of flour and sugar."
]

Disha Gawade 231A018

In [2]:
print("Disha Gawade 231A018")
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

Disha Gawade 231A018

In [6]:
print("Disha Gawade 231A018")
for i, document in enumerate(documents):
  print(f"D{i+1}: {document}")

Disha Gawade 231A018
D1: Solar panels convert sunlight into clean electricity.
D2: Renewable energy can be generated from the sun using solar cells.
D3: Electric vehicles help reduce greenhouse gas emissions in cities.
D4: Photovoltaic systems capture solar energy to power homes.
D5: Baking a cake requires precise measurements of flour and sugar.

In [8]:
print("Disha Gawade 231A018")
vectorize = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorize.fit_transform(documents)
print(tfidf_matrix.shape)

Disha Gawade 231A018
(5, 32)

In [9]:
print("Disha Gawade 231A018")
print(tfidf_matrix)

Disha Gawade 231A018
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 35 stored elements and shape (5, 32)>
  Coords	Values
  (0, 25)	0.28691207944979275
  (0, 18)	0.42841135808141123
  (0, 6)	0.42841135808141123
  (0, 28)	0.42841135808141123
  (0, 5)	0.42841135808141123
  (0, 8)	0.42841135808141123
  (1, 25)	0.27117099759647145
  (1, 23)	0.4049070906159763
  (1, 10)	0.3266764912066096
  (1, 13)	0.4049070906159763
  (1, 27)	0.4049070906159763
  (1, 30)	0.4049070906159763
  (1, 3)	0.4049070906159763
  (2, 7)	0.35355339059327373
  (2, 31)	0.35355339059327373
  (2, 15)	0.35355339059327373
  (2, 22)	0.35355339059327373
  (2, 14)	0.35355339059327373
  (2, 12)	0.35355339059327373
  (2, 9)	0.35355339059327373
  (2, 4)	0.35355339059327373
  (3, 25)	0.27117099759647145
  (3, 10)	0.3266764912066096
  (3, 19)	0.4049070906159763
  (3, 29)	0.4049070906159763
  (3, 2)	0.4049070906159763
  (3, 20)	0.4049070906159763
  (3, 16)	0.4049070906159763
  (4, 0)	0.3779644730092272
  (4, 1)	0.3779644730092272
  (4, 24)	0.3779644730092272
  (4, 21)	0.3779644730092272
  (4, 17)	0.3779644730092272
  (4, 11)	0.3779644730092272
  (4, 26)	0.3779644730092272

In [11]:
print("Disha Gawade 231A018")
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns = vectorize.get_feature_names_out(),
    index=["D1","D2","D3","D4","D5"]
)
tfidf_df.round(2)

Disha Gawade 231A018

,baking,cake,capture,cells,cities,clean,convert,electric,electricity,emissions,...,reduce,renewable,requires,solar,sugar,sun,sunlight,systems,using,vehicles
D1,0.00,0.00,0.0,0.0,0.00,0.43,0.43,0.00,0.43,0.00,...,0.00,0.0,0.00,0.29,0.00,0.0,0.43,0.0,0.0,0.00
D2,0.00,0.00,0.0,0.4,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.4,0.00,0.27,0.00,0.4,0.00,0.0,0.4,0.00
D3,0.00,0.00,0.0,0.0,0.35,0.00,0.00,0.35,0.00,0.35,...,0.35,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.35
D4,0.00,0.00,0.4,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.0,0.00,0.27,0.00,0.0,0.00,0.4,0.0,0.00
D5,0.38,0.38,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.0,0.38,0.00,0.38,0.0,0.00,0.0,0.0,0.00

In [13]:
print("Disha Gawade 231A018")
words= vectorize.get_feature_names_out()
print(words)

Disha Gawade 231A018
['baking' 'cake' 'capture' 'cells' 'cities' 'clean' 'convert' 'electric'
 'electricity' 'emissions' 'energy' 'flour' 'gas' 'generated' 'greenhouse'
 'help' 'homes' 'measurements' 'panels' 'photovoltaic' 'power' 'precise'
 'reduce' 'renewable' 'requires' 'solar' 'sugar' 'sun' 'sunlight'
 'systems' 'using' 'vehicles']

In [16]:
print("Disha Gawade 231A018")
print(len(words))

Disha Gawade 231A018
32

In [17]:
print("Disha Gawade 231A018")
similarity_matrix = cosine_similarity(tfidf_matrix)
similarity_matrix

Disha Gawade 231A018

array([[1.        , 0.07780223, 0.        , 0.07780223, 0.        ],
       [0.07780223, 1.        , 0.        , 0.18025124, 0.        ],
       [0.        , 0.        , 1.        , 0.        , 0.        ],
       [0.07780223, 0.18025124, 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ]])

In [18]:
print("Disha Gawade 231A018")
similarity_df = pd.DataFrame(
  similarity_matrix,
  index=["D1", "D2", "D3", "D4", "D5"],
  columns=["D1", "D2", "D3", "D4", "D5"]
)

similarity_df.round(3)

Disha Gawade 231A018

       D1     D2   D3     D4   D5
D1  1.000  0.078  0.0  0.078  0.0
D2  0.078  1.000  0.0  0.180  0.0
D3  0.000  0.000  1.0  0.000  0.0
D4  0.078  0.180  0.0  1.000  0.0
D5  0.000  0.000  0.0  0.000  1.0

In [21]:
print("Disha Gawade 231A018")
highest_similarity = -1
most_similar_pair = None

for i in range(len(documents)):
  for j in range(i + 1, len(documents)):

    similarity = similarity_matrix[i][j]

    if similarity > highest_similarity:
      highest_similarity = similarity
      most_similar_pair = (i, j)

print(
f"Most similar documents: "
f"D{most_similar_pair[0]+1} and D{most_similar_pair[1]+1}"
)
print(f"Similarity: {highest_similarity:.3f}")

Disha Gawade 231A018
Most similar documents: D2 and D4
Similarity: 0.180